export const USER_SLICE_LABEL = 'USER_SLICE_LABEL'
export const MENU_SLICE_LABEL = 'MENU_SLICE_LABEL'
export const CART_SLICE_LABEL = 'CART_SLICE_LABEL'
export const CHECKOUT_SLICE_LABEL = 'CHECKOUT_SLICE_LABEL'